name: CI - Vitest

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'   # only trigger when files in src/ are changed
  push:
    branches:
      - main
    paths:
      - 'src/**'   # only trigger when files in src/ are changed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm Install

      - name: Run tests
        run: npm run test
